# Aula 5 - Leyendo banco de datos

## **Creando un banco de datos local**

In [1]:
import sqlalchemy

In [2]:
from sqlalchemy import create_engine, MetaData, Table, inspect, text

In [3]:
engine = create_engine('sqlite:///:memory:')

## **Escribiendo en un banco de datos**

In [4]:
import pandas as pd

In [5]:
archivo = "clientes_banco.csv"

In [6]:
datos = pd.read_csv(archivo)

In [7]:
datos.head()

,ID_Cliente,Edad,Grado_estudio,Estado_civil,Tamaño_familia,Categoria_de_renta,Ocupacion,Años_empleado,Rendimiento_anual,Tiene_carro,Vivienda
0,5008804,32,Nivel superior,Relación-estable,2.0,Empleado,Otro,12.0,427500.0,1.0,Departamento alquilado
1,5008805,32,Nivel superior,Relación-estable,2.0,Empleado,Otro,12.0,427500.0,1.0,Departamento alquilado
2,5008806,58,Nivel intermedio,Casado,2.0,Empleado,Seguridad,3.0,112500.0,1.0,Casa/Departamento propio
3,5008808,52,Nivel intermedio,Soltero,1.0,Business Partner,Ventas,8.0,270000.0,0.0,Casa/Departamento propio
4,5008809,52,Nivel intermedio,Soltero,1.0,Business Partner,Ventas,8.0,270000.0,0.0,Casa/Departamento propio

In [8]:
datos.to_sql('clientes', engine, index=False)

95896

In [9]:
inspector = inspect(engine)

In [10]:
print(inspector.get_table_names())

['clientes']

## **Leyendo una consulta SQL**

In [11]:
query = "SELECT * FROM clientes WHERE Categoria_de_renta = 'Empleado'"

In [12]:
empleados = pd.read_sql(sql=text(query), con = engine.connect())

In [13]:
empleados

,ID_Cliente,Edad,Grado_estudio,Estado_civil,Tamaño_familia,Categoria_de_renta,Ocupacion,Años_empleado,Rendimiento_anual,Tiene_carro,Vivienda
0,5008804,32,Nivel superior,Relación-estable,2.0,Empleado,Otro,12.0,427500.0,1.0,Departamento alquilado
1,5008805,32,Nivel superior,Relación-estable,2.0,Empleado,Otro,12.0,427500.0,1.0,Departamento alquilado
2,5008806,58,Nivel intermedio,Casado,2.0,Empleado,Seguridad,3.0,112500.0,1.0,Casa/Departamento propio
3,5008815,46,Nivel superior,Casado,2.0,Empleado,Contabilidad,2.0,270000.0,1.0,Casa/Departamento propio
4,5112956,46,Nivel superior,Casado,2.0,Empleado,Contabilidad,2.0,270000.0,1.0,Casa/Departamento propio
...,...,...,...,...,...,...,...,...,...,...,...
48726,5713924,51,Nivel intermedio,Soltero,1.0,Empleado,Otro,5.0,180000.0,0.0,Casa/Departamento propio
48727,5713925,51,Nivel intermedio,Soltero,1.0,Empleado,Otro,5.0,180000.0,0.0,Casa/Departamento propio
48728,5713927,51,Nivel intermedio,Soltero,1.0,Empleado,Otro,5.0,180000.0,0.0,Casa/Departamento propio
48729,5713929,51,Nivel intermedio,Soltero,1.0,Empleado,Otro,5.0,180000.0,0.0,Casa/Departamento propio
48730,5713930,51,Nivel intermedio,Soltero,1.0,Empleado,Otro,5.0,180000.0,0.0,Casa/Departamento propio

In [14]:
empleados.to_sql('empleados', con = engine.connect(), index=False)

48731

In [15]:
pd.read_sql_table('empleados', con = engine.connect())

,ID_Cliente,Edad,Grado_estudio,Estado_civil,Tamaño_familia,Categoria_de_renta,Ocupacion,Años_empleado,Rendimiento_anual,Tiene_carro,Vivienda
0,5008804,32,Nivel superior,Relación-estable,2.0,Empleado,Otro,12.0,427500.0,1.0,Departamento alquilado
1,5008805,32,Nivel superior,Relación-estable,2.0,Empleado,Otro,12.0,427500.0,1.0,Departamento alquilado
2,5008806,58,Nivel intermedio,Casado,2.0,Empleado,Seguridad,3.0,112500.0,1.0,Casa/Departamento propio
3,5008815,46,Nivel superior,Casado,2.0,Empleado,Contabilidad,2.0,270000.0,1.0,Casa/Departamento propio
4,5112956,46,Nivel superior,Casado,2.0,Empleado,Contabilidad,2.0,270000.0,1.0,Casa/Departamento propio
...,...,...,...,...,...,...,...,...,...,...,...
48726,5713924,51,Nivel intermedio,Soltero,1.0,Empleado,Otro,5.0,180000.0,0.0,Casa/Departamento propio
48727,5713925,51,Nivel intermedio,Soltero,1.0,Empleado,Otro,5.0,180000.0,0.0,Casa/Departamento propio
48728,5713927,51,Nivel intermedio,Soltero,1.0,Empleado,Otro,5.0,180000.0,0.0,Casa/Departamento propio
48729,5713929,51,Nivel intermedio,Soltero,1.0,Empleado,Otro,5.0,180000.0,0.0,Casa/Departamento propio
48730,5713930,51,Nivel intermedio,Soltero,1.0,Empleado,Otro,5.0,180000.0,0.0,Casa/Departamento propio

In [19]:
pd.read_sql_table('empleados', con = engine.connect(), columns=['ID_Cliente', 'Grado_estudio', 'Rendimiento_anual'])

       ID_Cliente     Grado_estudio  Rendimiento_anual
0         5008804    Nivel superior           427500.0
1         5008805    Nivel superior           427500.0
2         5008806  Nivel intermedio           112500.0
3         5008815    Nivel superior           270000.0
4         5112956    Nivel superior           270000.0
...           ...               ...                ...
48726     5713924  Nivel intermedio           180000.0
48727     5713925  Nivel intermedio           180000.0
48728     5713927  Nivel intermedio           180000.0
48729     5713929  Nivel intermedio           180000.0
48730     5713930  Nivel intermedio           180000.0

[48731 rows x 3 columns]

In [20]:
query = 'SELECT * FROM clientes'

In [21]:
pd.read_sql(sql=text(query), con = engine.connect())

,ID_Cliente,Edad,Grado_estudio,Estado_civil,Tamaño_familia,Categoria_de_renta,Ocupacion,Años_empleado,Rendimiento_anual,Tiene_carro,Vivienda
0,5008804,32,Nivel superior,Relación-estable,2.0,Empleado,Otro,12.0,427500.0,1.0,Departamento alquilado
1,5008805,32,Nivel superior,Relación-estable,2.0,Empleado,Otro,12.0,427500.0,1.0,Departamento alquilado
2,5008806,58,Nivel intermedio,Casado,2.0,Empleado,Seguridad,3.0,112500.0,1.0,Casa/Departamento propio
3,5008808,52,Nivel intermedio,Soltero,1.0,Business Partner,Ventas,8.0,270000.0,0.0,Casa/Departamento propio
4,5008809,52,Nivel intermedio,Soltero,1.0,Business Partner,Ventas,8.0,270000.0,0.0,Casa/Departamento propio
...,...,...,...,...,...,...,...,...,...,...,...
95891,5713925,51,Nivel intermedio,Soltero,1.0,Empleado,Otro,5.0,180000.0,0.0,Casa/Departamento propio
95892,5713927,51,Nivel intermedio,Soltero,1.0,Empleado,Otro,5.0,180000.0,0.0,Casa/Departamento propio
95893,5713929,51,Nivel intermedio,Soltero,1.0,Empleado,Otro,5.0,180000.0,0.0,Casa/Departamento propio
95894,5713930,51,Nivel intermedio,Soltero,1.0,Empleado,Otro,5.0,180000.0,0.0,Casa/Departamento propio
95895,5713931,51,Nivel intermedio,Soltero,NaN,None,None,NaN,NaN,NaN,None

In [23]:
#Borrando registros

from sqlalchemy.exc import SQLAlchemyError
query = 'DELETE FROM clientes WHERE ID_Cliente = 5008804'
try:
   r_set = engine.connect().execute(text(query))
except SQLAlchemyError as e:
    print(e)
else:
    print('Registro borrado:', r_set.rowcount)

Registro borrado: 1

In [24]:
pd.read_sql_table('clientes', con = engine.connect())

,ID_Cliente,Edad,Grado_estudio,Estado_civil,Tamaño_familia,Categoria_de_renta,Ocupacion,Años_empleado,Rendimiento_anual,Tiene_carro,Vivienda
0,5008805,32,Nivel superior,Relación-estable,2.0,Empleado,Otro,12.0,427500.0,1.0,Departamento alquilado
1,5008806,58,Nivel intermedio,Casado,2.0,Empleado,Seguridad,3.0,112500.0,1.0,Casa/Departamento propio
2,5008808,52,Nivel intermedio,Soltero,1.0,Business Partner,Ventas,8.0,270000.0,0.0,Casa/Departamento propio
3,5008809,52,Nivel intermedio,Soltero,1.0,Business Partner,Ventas,8.0,270000.0,0.0,Casa/Departamento propio
4,5008810,52,Nivel intermedio,Soltero,1.0,Business Partner,Ventas,8.0,270000.0,0.0,Casa/Departamento propio
...,...,...,...,...,...,...,...,...,...,...,...
95890,5713925,51,Nivel intermedio,Soltero,1.0,Empleado,Otro,5.0,180000.0,0.0,Casa/Departamento propio
95891,5713927,51,Nivel intermedio,Soltero,1.0,Empleado,Otro,5.0,180000.0,0.0,Casa/Departamento propio
95892,5713929,51,Nivel intermedio,Soltero,1.0,Empleado,Otro,5.0,180000.0,0.0,Casa/Departamento propio
95893,5713930,51,Nivel intermedio,Soltero,1.0,Empleado,Otro,5.0,180000.0,0.0,Casa/Departamento propio
95894,5713931,51,Nivel intermedio,Soltero,NaN,None,None,NaN,NaN,NaN,None

In [25]:
#Actualizando registros

query = 'UPDATE clientes SET Grado_estudio="Nivel superior" WHERE ID_Cliente = 5008808'
try:
   r_set = engine.connect().execute(text(query))
except SQLAlchemyError as e:
    print(e)
else:
    print('Registros actualizados:', r_set.rowcount)

Registros actualizados: 1

In [26]:
pd.read_sql_table('clientes', con = engine.connect())

,ID_Cliente,Edad,Grado_estudio,Estado_civil,Tamaño_familia,Categoria_de_renta,Ocupacion,Años_empleado,Rendimiento_anual,Tiene_carro,Vivienda
0,5008805,32,Nivel superior,Relación-estable,2.0,Empleado,Otro,12.0,427500.0,1.0,Departamento alquilado
1,5008806,58,Nivel intermedio,Casado,2.0,Empleado,Seguridad,3.0,112500.0,1.0,Casa/Departamento propio
2,5008808,52,Nivel superior,Soltero,1.0,Business Partner,Ventas,8.0,270000.0,0.0,Casa/Departamento propio
3,5008809,52,Nivel intermedio,Soltero,1.0,Business Partner,Ventas,8.0,270000.0,0.0,Casa/Departamento propio
4,5008810,52,Nivel intermedio,Soltero,1.0,Business Partner,Ventas,8.0,270000.0,0.0,Casa/Departamento propio
...,...,...,...,...,...,...,...,...,...,...,...
95890,5713925,51,Nivel intermedio,Soltero,1.0,Empleado,Otro,5.0,180000.0,0.0,Casa/Departamento propio
95891,5713927,51,Nivel intermedio,Soltero,1.0,Empleado,Otro,5.0,180000.0,0.0,Casa/Departamento propio
95892,5713929,51,Nivel intermedio,Soltero,1.0,Empleado,Otro,5.0,180000.0,0.0,Casa/Departamento propio
95893,5713930,51,Nivel intermedio,Soltero,1.0,Empleado,Otro,5.0,180000.0,0.0,Casa/Departamento propio
95894,5713931,51,Nivel intermedio,Soltero,NaN,None,None,NaN,NaN,NaN,None

In [27]:
inspector = inspect(engine)
print(inspector.get_table_names())

['clientes', 'empleados']